CREATE TABLE IF NOT EXISTS donations (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    donation_id CHAR(36) NOT NULL UNIQUE,
    donor_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    food_type ENUM('VEG','NON_VEG','BOTH') NOT NULL,
    quantity VARCHAR(100) NOT NULL,
    serves_people INT,
    expiry_time TIMESTAMP NOT NULL,
    address VARCHAR(500) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    pincode VARCHAR(10),
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    status ENUM('AVAILABLE','CLAIMED','PICKED_UP','DELIVERED','EXPIRED','CANCELLED') NOT NULL DEFAULT 'AVAILABLE',
    image_url VARCHAR(500),
    pickup_instructions TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_donor_id (donor_id),
    INDEX idx_status (status),
    INDEX idx_city (city),
    CONSTRAINT fk_donation_donor FOREIGN KEY (donor_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
