CREATE TABLE IF NOT EXISTS deliveries (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    delivery_id CHAR(36) NOT NULL UNIQUE,
    claim_id BIGINT NOT NULL UNIQUE,
    volunteer_id BIGINT,
    status ENUM('ASSIGNED','PICKED_UP','IN_TRANSIT','DELIVERED','FAILED') NOT NULL DEFAULT 'ASSIGNED',
    pickup_time TIMESTAMP NULL,
    delivery_time TIMESTAMP NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_delivery_claim FOREIGN KEY (claim_id) REFERENCES claims(id),
    CONSTRAINT fk_delivery_volunteer FOREIGN KEY (volunteer_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
